apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsvp    
spec: 
  replicas: 3
  template:
    metadata:
      labels:
        app: rsvp
    spec:
      containers:
      - name: rsvp-app
        image: prasanna1994/rsvp
        env:
        - name: MONGODB_HOST
          value: mongodb
        ports:
        - containerPort: 5000
          name: web-port
